ALTER TABLE shops ADD COLUMN delivery_radius_km DOUBLE PRECISION NOT NULL DEFAULT 5;
ALTER TABLE addresses ADD COLUMN latitude DOUBLE PRECISION;
ALTER TABLE addresses ADD COLUMN longitude DOUBLE PRECISION;