ALTER TABLE shops ALTER COLUMN latitude TYPE DOUBLE PRECISION;
ALTER TABLE shops ALTER COLUMN longitude TYPE DOUBLE PRECISION;
ALTER TABLE orders ALTER COLUMN delivery_lat TYPE DOUBLE PRECISION;
ALTER TABLE orders ALTER COLUMN delivery_lng TYPE DOUBLE PRECISION;